package net.renfei.server.core.repositories.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   用户操作审计日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_audit_log
 */
public class SysAuditLogWithBLOBs extends SysAuditLog implements Serializable {
    /**
     * Database Column Remarks:
     *   用户代理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.client_user_agent
     *
     * @mbg.generated
     */
    private String clientUserAgent;

    /**
     * Database Column Remarks:
     *   请求来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.request_referer
     *
     * @mbg.generated
     */
    private String requestReferer;

    /**
     * Database Column Remarks:
     *   请求参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.request_parameter
     *
     * @mbg.generated
     */
    private String requestParameter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.client_user_agent
     *
     * @return the value of sys_audit_log.client_user_agent
     *
     * @mbg.generated
     */
    public String getClientUserAgent() {
        return clientUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.client_user_agent
     *
     * @param clientUserAgent the value for sys_audit_log.client_user_agent
     *
     * @mbg.generated
     */
    public void setClientUserAgent(String clientUserAgent) {
        this.clientUserAgent = clientUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.request_referer
     *
     * @return the value of sys_audit_log.request_referer
     *
     * @mbg.generated
     */
    public String getRequestReferer() {
        return requestReferer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.request_referer
     *
     * @param requestReferer the value for sys_audit_log.request_referer
     *
     * @mbg.generated
     */
    public void setRequestReferer(String requestReferer) {
        this.requestReferer = requestReferer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.request_parameter
     *
     * @return the value of sys_audit_log.request_parameter
     *
     * @mbg.generated
     */
    public String getRequestParameter() {
        return requestParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.request_parameter
     *
     * @param requestParameter the value for sys_audit_log.request_parameter
     *
     * @mbg.generated
     */
    public void setRequestParameter(String requestParameter) {
        this.requestParameter = requestParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientUserAgent=").append(clientUserAgent);
        sb.append(", requestReferer=").append(requestReferer);
        sb.append(", requestParameter=").append(requestParameter);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysAuditLogWithBLOBs other = (SysAuditLogWithBLOBs) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()))
            && (this.getLogLevel() == null ? other.getLogLevel() == null : this.getLogLevel().equals(other.getLogLevel()))
            && (this.getModule() == null ? other.getModule() == null : this.getModule().equals(other.getModule()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getOperation() == null ? other.getOperation() == null : this.getOperation().equals(other.getOperation()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getExecutionTime() == null ? other.getExecutionTime() == null : this.getExecutionTime().equals(other.getExecutionTime()))
            && (this.getRequestMethod() == null ? other.getRequestMethod() == null : this.getRequestMethod().equals(other.getRequestMethod()))
            && (this.getRequestUri() == null ? other.getRequestUri() == null : this.getRequestUri().equals(other.getRequestUri()))
            && (this.getClientIp() == null ? other.getClientIp() == null : this.getClientIp().equals(other.getClientIp()))
            && (this.getClientUserAgent() == null ? other.getClientUserAgent() == null : this.getClientUserAgent().equals(other.getClientUserAgent()))
            && (this.getRequestReferer() == null ? other.getRequestReferer() == null : this.getRequestReferer().equals(other.getRequestReferer()))
            && (this.getRequestParameter() == null ? other.getRequestParameter() == null : this.getRequestParameter().equals(other.getRequestParameter()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        result = prime * result + ((getLogLevel() == null) ? 0 : getLogLevel().hashCode());
        result = prime * result + ((getModule() == null) ? 0 : getModule().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getOperation() == null) ? 0 : getOperation().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getExecutionTime() == null) ? 0 : getExecutionTime().hashCode());
        result = prime * result + ((getRequestMethod() == null) ? 0 : getRequestMethod().hashCode());
        result = prime * result + ((getRequestUri() == null) ? 0 : getRequestUri().hashCode());
        result = prime * result + ((getClientIp() == null) ? 0 : getClientIp().hashCode());
        result = prime * result + ((getClientUserAgent() == null) ? 0 : getClientUserAgent().hashCode());
        result = prime * result + ((getRequestReferer() == null) ? 0 : getRequestReferer().hashCode());
        result = prime * result + ((getRequestParameter() == null) ? 0 : getRequestParameter().hashCode());
        return result;
    }
}