package net.renfei.server.core.repositories.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户操作审计日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_audit_log
 */
public class SysAuditLog implements Serializable {
    /**
     * Database Column Remarks:
     *   UUID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   日志时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.log_time
     *
     * @mbg.generated
     */
    private Date logTime;

    /**
     * Database Column Remarks:
     *   日志等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.log_level
     *
     * @mbg.generated
     */
    private String logLevel;

    /**
     * Database Column Remarks:
     *   模块
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.module
     *
     * @mbg.generated
     */
    private String module;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   操作
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.operation
     *
     * @mbg.generated
     */
    private String operation;

    /**
     * Database Column Remarks:
     *   详细描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   执行时间(毫秒)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.execution_time
     *
     * @mbg.generated
     */
    private Long executionTime;

    /**
     * Database Column Remarks:
     *   请求方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.request_method
     *
     * @mbg.generated
     */
    private String requestMethod;

    /**
     * Database Column Remarks:
     *   请求地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.request_uri
     *
     * @mbg.generated
     */
    private String requestUri;

    /**
     * Database Column Remarks:
     *   客户端IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_audit_log.client_ip
     *
     * @mbg.generated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.uuid
     *
     * @return the value of sys_audit_log.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.uuid
     *
     * @param uuid the value for sys_audit_log.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.log_time
     *
     * @return the value of sys_audit_log.log_time
     *
     * @mbg.generated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.log_time
     *
     * @param logTime the value for sys_audit_log.log_time
     *
     * @mbg.generated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.log_level
     *
     * @return the value of sys_audit_log.log_level
     *
     * @mbg.generated
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.log_level
     *
     * @param logLevel the value for sys_audit_log.log_level
     *
     * @mbg.generated
     */
    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.module
     *
     * @return the value of sys_audit_log.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.module
     *
     * @param module the value for sys_audit_log.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.username
     *
     * @return the value of sys_audit_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.username
     *
     * @param username the value for sys_audit_log.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.operation
     *
     * @return the value of sys_audit_log.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.operation
     *
     * @param operation the value for sys_audit_log.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.description
     *
     * @return the value of sys_audit_log.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.description
     *
     * @param description the value for sys_audit_log.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.execution_time
     *
     * @return the value of sys_audit_log.execution_time
     *
     * @mbg.generated
     */
    public Long getExecutionTime() {
        return executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.execution_time
     *
     * @param executionTime the value for sys_audit_log.execution_time
     *
     * @mbg.generated
     */
    public void setExecutionTime(Long executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.request_method
     *
     * @return the value of sys_audit_log.request_method
     *
     * @mbg.generated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.request_method
     *
     * @param requestMethod the value for sys_audit_log.request_method
     *
     * @mbg.generated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.request_uri
     *
     * @return the value of sys_audit_log.request_uri
     *
     * @mbg.generated
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.request_uri
     *
     * @param requestUri the value for sys_audit_log.request_uri
     *
     * @mbg.generated
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_audit_log.client_ip
     *
     * @return the value of sys_audit_log.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_audit_log.client_ip
     *
     * @param clientIp the value for sys_audit_log.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", logTime=").append(logTime);
        sb.append(", logLevel=").append(logLevel);
        sb.append(", module=").append(module);
        sb.append(", username=").append(username);
        sb.append(", operation=").append(operation);
        sb.append(", description=").append(description);
        sb.append(", executionTime=").append(executionTime);
        sb.append(", requestMethod=").append(requestMethod);
        sb.append(", requestUri=").append(requestUri);
        sb.append(", clientIp=").append(clientIp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysAuditLog other = (SysAuditLog) that;
        return (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()))
            && (this.getLogLevel() == null ? other.getLogLevel() == null : this.getLogLevel().equals(other.getLogLevel()))
            && (this.getModule() == null ? other.getModule() == null : this.getModule().equals(other.getModule()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getOperation() == null ? other.getOperation() == null : this.getOperation().equals(other.getOperation()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getExecutionTime() == null ? other.getExecutionTime() == null : this.getExecutionTime().equals(other.getExecutionTime()))
            && (this.getRequestMethod() == null ? other.getRequestMethod() == null : this.getRequestMethod().equals(other.getRequestMethod()))
            && (this.getRequestUri() == null ? other.getRequestUri() == null : this.getRequestUri().equals(other.getRequestUri()))
            && (this.getClientIp() == null ? other.getClientIp() == null : this.getClientIp().equals(other.getClientIp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        result = prime * result + ((getLogLevel() == null) ? 0 : getLogLevel().hashCode());
        result = prime * result + ((getModule() == null) ? 0 : getModule().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getOperation() == null) ? 0 : getOperation().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getExecutionTime() == null) ? 0 : getExecutionTime().hashCode());
        result = prime * result + ((getRequestMethod() == null) ? 0 : getRequestMethod().hashCode());
        result = prime * result + ((getRequestUri() == null) ? 0 : getRequestUri().hashCode());
        result = prime * result + ((getClientIp() == null) ? 0 : getClientIp().hashCode());
        return result;
    }
}