package net.renfei.server.core.repositories.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   系统菜单权限资源
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_menu
 */
public class SysMenuWithBLOBs extends SysMenu implements Serializable {
    /**
     * Database Column Remarks:
     *   前端使用：CSS样式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_css
     *
     * @mbg.generated
     */
    private String menuCss;

    /**
     * Database Column Remarks:
     *   前端使用：扩展预留
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.extend_json
     *
     * @mbg.generated
     */
    private String extendJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_css
     *
     * @return the value of sys_menu.menu_css
     *
     * @mbg.generated
     */
    public String getMenuCss() {
        return menuCss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_css
     *
     * @param menuCss the value for sys_menu.menu_css
     *
     * @mbg.generated
     */
    public void setMenuCss(String menuCss) {
        this.menuCss = menuCss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.extend_json
     *
     * @return the value of sys_menu.extend_json
     *
     * @mbg.generated
     */
    public String getExtendJson() {
        return extendJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.extend_json
     *
     * @param extendJson the value for sys_menu.extend_json
     *
     * @mbg.generated
     */
    public void setExtendJson(String extendJson) {
        this.extendJson = extendJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuCss=").append(menuCss);
        sb.append(", extendJson=").append(extendJson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMenuWithBLOBs other = (SysMenuWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getMenuType() == null ? other.getMenuType() == null : this.getMenuType().equals(other.getMenuType()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getMenuIcon() == null ? other.getMenuIcon() == null : this.getMenuIcon().equals(other.getMenuIcon()))
            && (this.getMenuLink() == null ? other.getMenuLink() == null : this.getMenuLink().equals(other.getMenuLink()))
            && (this.getMenuTarget() == null ? other.getMenuTarget() == null : this.getMenuTarget().equals(other.getMenuTarget()))
            && (this.getMenuClass() == null ? other.getMenuClass() == null : this.getMenuClass().equals(other.getMenuClass()))
            && (this.getMenuTitle() == null ? other.getMenuTitle() == null : this.getMenuTitle().equals(other.getMenuTitle()))
            && (this.getMenuOnclick() == null ? other.getMenuOnclick() == null : this.getMenuOnclick().equals(other.getMenuOnclick()))
            && (this.getMenuOrder() == null ? other.getMenuOrder() == null : this.getMenuOrder().equals(other.getMenuOrder()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAuthority() == null ? other.getAuthority() == null : this.getAuthority().equals(other.getAuthority()))
            && (this.getMenuCss() == null ? other.getMenuCss() == null : this.getMenuCss().equals(other.getMenuCss()))
            && (this.getExtendJson() == null ? other.getExtendJson() == null : this.getExtendJson().equals(other.getExtendJson()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getMenuType() == null) ? 0 : getMenuType().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getMenuIcon() == null) ? 0 : getMenuIcon().hashCode());
        result = prime * result + ((getMenuLink() == null) ? 0 : getMenuLink().hashCode());
        result = prime * result + ((getMenuTarget() == null) ? 0 : getMenuTarget().hashCode());
        result = prime * result + ((getMenuClass() == null) ? 0 : getMenuClass().hashCode());
        result = prime * result + ((getMenuTitle() == null) ? 0 : getMenuTitle().hashCode());
        result = prime * result + ((getMenuOnclick() == null) ? 0 : getMenuOnclick().hashCode());
        result = prime * result + ((getMenuOrder() == null) ? 0 : getMenuOrder().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAuthority() == null) ? 0 : getAuthority().hashCode());
        result = prime * result + ((getMenuCss() == null) ? 0 : getMenuCss().hashCode());
        result = prime * result + ((getExtendJson() == null) ? 0 : getExtendJson().hashCode());
        return result;
    }
}