package net.renfei.server.core.repositories.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   系统用户
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 */
public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   一次性密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.totp
     *
     * @mbg.generated
     */
    private String totp;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   办公地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.office_address
     *
     * @mbg.generated
     */
    private String officeAddress;

    /**
     * Database Column Remarks:
     *   办公电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.office_phone
     *
     * @mbg.generated
     */
    private String officePhone;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   用户状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_status
     *
     * @mbg.generated
     */
    private Integer userStatus;

    /**
     * Database Column Remarks:
     *   锁定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.lock_time
     *
     * @mbg.generated
     */
    private Date lockTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   密码错误次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.error_count
     *
     * @mbg.generated
     */
    private Integer errorCount;

    /**
     * Database Column Remarks:
     *   密码修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password_update_time
     *
     * @mbg.generated
     */
    private Date passwordUpdateTime;

    /**
     * Database Column Remarks:
     *   是否是内置用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.built_in
     *
     * @mbg.generated
     */
    private Boolean builtIn;

    /**
     * Database Column Remarks:
     *   注册IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.registration_ip
     *
     * @mbg.generated
     */
    private String registrationIp;

    /**
     * Database Column Remarks:
     *   保密等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.secret_level
     *
     * @mbg.generated
     */
    private Integer secretLevel;

    /**
     * Database Column Remarks:
     *   是否锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.locked
     *
     * @mbg.generated
     */
    private Boolean locked;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     * Database Column Remarks:
     *   密码过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password_expiration_time
     *
     * @mbg.generated
     */
    private Date passwordExpirationTime;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birth_day
     *
     * @mbg.generated
     */
    private Date birthDay;

    /**
     * Database Column Remarks:
     *   职务
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * Database Column Remarks:
     *   学历
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     * Database Column Remarks:
     *   家庭住址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     * Database Column Remarks:
     *   家庭电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.home_phone
     *
     * @mbg.generated
     */
    private String homePhone;

    /**
     * Database Column Remarks:
     *   政治面貌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.political_status
     *
     * @mbg.generated
     */
    private String politicalStatus;

    /**
     * Database Column Remarks:
     *   专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.professional
     *
     * @mbg.generated
     */
    private String professional;

    /**
     * Database Column Remarks:
     *   参加工作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.work_date
     *
     * @mbg.generated
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.totp
     *
     * @return the value of sys_user.totp
     *
     * @mbg.generated
     */
    public String getTotp() {
        return totp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.totp
     *
     * @param totp the value for sys_user.totp
     *
     * @mbg.generated
     */
    public void setTotp(String totp) {
        this.totp = totp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobile
     *
     * @return the value of sys_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobile
     *
     * @param mobile the value for sys_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.gender
     *
     * @return the value of sys_user.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.gender
     *
     * @param gender the value for sys_user.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.office_address
     *
     * @return the value of sys_user.office_address
     *
     * @mbg.generated
     */
    public String getOfficeAddress() {
        return officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.office_address
     *
     * @param officeAddress the value for sys_user.office_address
     *
     * @mbg.generated
     */
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.office_phone
     *
     * @return the value of sys_user.office_phone
     *
     * @mbg.generated
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.office_phone
     *
     * @param officePhone the value for sys_user.office_phone
     *
     * @mbg.generated
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_status
     *
     * @return the value of sys_user.user_status
     *
     * @mbg.generated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_status
     *
     * @param userStatus the value for sys_user.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.lock_time
     *
     * @return the value of sys_user.lock_time
     *
     * @mbg.generated
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.lock_time
     *
     * @param lockTime the value for sys_user.lock_time
     *
     * @mbg.generated
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.error_count
     *
     * @return the value of sys_user.error_count
     *
     * @mbg.generated
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.error_count
     *
     * @param errorCount the value for sys_user.error_count
     *
     * @mbg.generated
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password_update_time
     *
     * @return the value of sys_user.password_update_time
     *
     * @mbg.generated
     */
    public Date getPasswordUpdateTime() {
        return passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password_update_time
     *
     * @param passwordUpdateTime the value for sys_user.password_update_time
     *
     * @mbg.generated
     */
    public void setPasswordUpdateTime(Date passwordUpdateTime) {
        this.passwordUpdateTime = passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.built_in
     *
     * @return the value of sys_user.built_in
     *
     * @mbg.generated
     */
    public Boolean getBuiltIn() {
        return builtIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.built_in
     *
     * @param builtIn the value for sys_user.built_in
     *
     * @mbg.generated
     */
    public void setBuiltIn(Boolean builtIn) {
        this.builtIn = builtIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.registration_ip
     *
     * @return the value of sys_user.registration_ip
     *
     * @mbg.generated
     */
    public String getRegistrationIp() {
        return registrationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.registration_ip
     *
     * @param registrationIp the value for sys_user.registration_ip
     *
     * @mbg.generated
     */
    public void setRegistrationIp(String registrationIp) {
        this.registrationIp = registrationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.secret_level
     *
     * @return the value of sys_user.secret_level
     *
     * @mbg.generated
     */
    public Integer getSecretLevel() {
        return secretLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.secret_level
     *
     * @param secretLevel the value for sys_user.secret_level
     *
     * @mbg.generated
     */
    public void setSecretLevel(Integer secretLevel) {
        this.secretLevel = secretLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.locked
     *
     * @return the value of sys_user.locked
     *
     * @mbg.generated
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.locked
     *
     * @param locked the value for sys_user.locked
     *
     * @mbg.generated
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.enabled
     *
     * @return the value of sys_user.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.enabled
     *
     * @param enabled the value for sys_user.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password_expiration_time
     *
     * @return the value of sys_user.password_expiration_time
     *
     * @mbg.generated
     */
    public Date getPasswordExpirationTime() {
        return passwordExpirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password_expiration_time
     *
     * @param passwordExpirationTime the value for sys_user.password_expiration_time
     *
     * @mbg.generated
     */
    public void setPasswordExpirationTime(Date passwordExpirationTime) {
        this.passwordExpirationTime = passwordExpirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.description
     *
     * @return the value of sys_user.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.description
     *
     * @param description the value for sys_user.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birth_day
     *
     * @return the value of sys_user.birth_day
     *
     * @mbg.generated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birth_day
     *
     * @param birthDay the value for sys_user.birth_day
     *
     * @mbg.generated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.duty
     *
     * @return the value of sys_user.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.duty
     *
     * @param duty the value for sys_user.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.education
     *
     * @return the value of sys_user.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.education
     *
     * @param education the value for sys_user.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.home_address
     *
     * @return the value of sys_user.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.home_address
     *
     * @param homeAddress the value for sys_user.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.home_phone
     *
     * @return the value of sys_user.home_phone
     *
     * @mbg.generated
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.home_phone
     *
     * @param homePhone the value for sys_user.home_phone
     *
     * @mbg.generated
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.political_status
     *
     * @return the value of sys_user.political_status
     *
     * @mbg.generated
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.political_status
     *
     * @param politicalStatus the value for sys_user.political_status
     *
     * @mbg.generated
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.professional
     *
     * @return the value of sys_user.professional
     *
     * @mbg.generated
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.professional
     *
     * @param professional the value for sys_user.professional
     *
     * @mbg.generated
     */
    public void setProfessional(String professional) {
        this.professional = professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.work_date
     *
     * @return the value of sys_user.work_date
     *
     * @mbg.generated
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.work_date
     *
     * @param workDate the value for sys_user.work_date
     *
     * @mbg.generated
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", totp=").append(totp);
        sb.append(", name=").append(name);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", gender=").append(gender);
        sb.append(", officeAddress=").append(officeAddress);
        sb.append(", officePhone=").append(officePhone);
        sb.append(", createTime=").append(createTime);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", errorCount=").append(errorCount);
        sb.append(", passwordUpdateTime=").append(passwordUpdateTime);
        sb.append(", builtIn=").append(builtIn);
        sb.append(", registrationIp=").append(registrationIp);
        sb.append(", secretLevel=").append(secretLevel);
        sb.append(", locked=").append(locked);
        sb.append(", enabled=").append(enabled);
        sb.append(", passwordExpirationTime=").append(passwordExpirationTime);
        sb.append(", description=").append(description);
        sb.append(", birthDay=").append(birthDay);
        sb.append(", duty=").append(duty);
        sb.append(", education=").append(education);
        sb.append(", homeAddress=").append(homeAddress);
        sb.append(", homePhone=").append(homePhone);
        sb.append(", politicalStatus=").append(politicalStatus);
        sb.append(", professional=").append(professional);
        sb.append(", workDate=").append(workDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysUser other = (SysUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getTotp() == null ? other.getTotp() == null : this.getTotp().equals(other.getTotp()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getOfficeAddress() == null ? other.getOfficeAddress() == null : this.getOfficeAddress().equals(other.getOfficeAddress()))
            && (this.getOfficePhone() == null ? other.getOfficePhone() == null : this.getOfficePhone().equals(other.getOfficePhone()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getLockTime() == null ? other.getLockTime() == null : this.getLockTime().equals(other.getLockTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getErrorCount() == null ? other.getErrorCount() == null : this.getErrorCount().equals(other.getErrorCount()))
            && (this.getPasswordUpdateTime() == null ? other.getPasswordUpdateTime() == null : this.getPasswordUpdateTime().equals(other.getPasswordUpdateTime()))
            && (this.getBuiltIn() == null ? other.getBuiltIn() == null : this.getBuiltIn().equals(other.getBuiltIn()))
            && (this.getRegistrationIp() == null ? other.getRegistrationIp() == null : this.getRegistrationIp().equals(other.getRegistrationIp()))
            && (this.getSecretLevel() == null ? other.getSecretLevel() == null : this.getSecretLevel().equals(other.getSecretLevel()))
            && (this.getLocked() == null ? other.getLocked() == null : this.getLocked().equals(other.getLocked()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getPasswordExpirationTime() == null ? other.getPasswordExpirationTime() == null : this.getPasswordExpirationTime().equals(other.getPasswordExpirationTime()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getBirthDay() == null ? other.getBirthDay() == null : this.getBirthDay().equals(other.getBirthDay()))
            && (this.getDuty() == null ? other.getDuty() == null : this.getDuty().equals(other.getDuty()))
            && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
            && (this.getHomeAddress() == null ? other.getHomeAddress() == null : this.getHomeAddress().equals(other.getHomeAddress()))
            && (this.getHomePhone() == null ? other.getHomePhone() == null : this.getHomePhone().equals(other.getHomePhone()))
            && (this.getPoliticalStatus() == null ? other.getPoliticalStatus() == null : this.getPoliticalStatus().equals(other.getPoliticalStatus()))
            && (this.getProfessional() == null ? other.getProfessional() == null : this.getProfessional().equals(other.getProfessional()))
            && (this.getWorkDate() == null ? other.getWorkDate() == null : this.getWorkDate().equals(other.getWorkDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getTotp() == null) ? 0 : getTotp().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getOfficeAddress() == null) ? 0 : getOfficeAddress().hashCode());
        result = prime * result + ((getOfficePhone() == null) ? 0 : getOfficePhone().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getLockTime() == null) ? 0 : getLockTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getErrorCount() == null) ? 0 : getErrorCount().hashCode());
        result = prime * result + ((getPasswordUpdateTime() == null) ? 0 : getPasswordUpdateTime().hashCode());
        result = prime * result + ((getBuiltIn() == null) ? 0 : getBuiltIn().hashCode());
        result = prime * result + ((getRegistrationIp() == null) ? 0 : getRegistrationIp().hashCode());
        result = prime * result + ((getSecretLevel() == null) ? 0 : getSecretLevel().hashCode());
        result = prime * result + ((getLocked() == null) ? 0 : getLocked().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getPasswordExpirationTime() == null) ? 0 : getPasswordExpirationTime().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getBirthDay() == null) ? 0 : getBirthDay().hashCode());
        result = prime * result + ((getDuty() == null) ? 0 : getDuty().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getHomeAddress() == null) ? 0 : getHomeAddress().hashCode());
        result = prime * result + ((getHomePhone() == null) ? 0 : getHomePhone().hashCode());
        result = prime * result + ((getPoliticalStatus() == null) ? 0 : getPoliticalStatus().hashCode());
        result = prime * result + ((getProfessional() == null) ? 0 : getProfessional().hashCode());
        result = prime * result + ((getWorkDate() == null) ? 0 : getWorkDate().hashCode());
        return result;
    }
}