package net.renfei.server.member.repositories.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   会员表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member
 */
public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   一次性密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.totp
     *
     * @mbg.generated
     */
    private String totp;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   用户状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.user_status
     *
     * @mbg.generated
     */
    private Integer userStatus;

    /**
     * Database Column Remarks:
     *   锁定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.lock_time
     *
     * @mbg.generated
     */
    private Date lockTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   密码错误次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.error_count
     *
     * @mbg.generated
     */
    private Integer errorCount;

    /**
     * Database Column Remarks:
     *   密码修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password_update_time
     *
     * @mbg.generated
     */
    private Date passwordUpdateTime;

    /**
     * Database Column Remarks:
     *   注册IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.registration_ip
     *
     * @mbg.generated
     */
    private String registrationIp;

    /**
     * Database Column Remarks:
     *   是否锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.locked
     *
     * @mbg.generated
     */
    private Boolean locked;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     * Database Column Remarks:
     *   密码过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password_expiration_time
     *
     * @mbg.generated
     */
    private Date passwordExpirationTime;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth_day
     *
     * @mbg.generated
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.username
     *
     * @return the value of member.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.username
     *
     * @param username the value for member.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.totp
     *
     * @return the value of member.totp
     *
     * @mbg.generated
     */
    public String getTotp() {
        return totp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.totp
     *
     * @param totp the value for member.totp
     *
     * @mbg.generated
     */
    public void setTotp(String totp) {
        this.totp = totp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param createTime the value for member.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.user_status
     *
     * @return the value of member.user_status
     *
     * @mbg.generated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.user_status
     *
     * @param userStatus the value for member.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.lock_time
     *
     * @return the value of member.lock_time
     *
     * @mbg.generated
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.lock_time
     *
     * @param lockTime the value for member.lock_time
     *
     * @mbg.generated
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_time
     *
     * @return the value of member.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_time
     *
     * @param updateTime the value for member.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.error_count
     *
     * @return the value of member.error_count
     *
     * @mbg.generated
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.error_count
     *
     * @param errorCount the value for member.error_count
     *
     * @mbg.generated
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password_update_time
     *
     * @return the value of member.password_update_time
     *
     * @mbg.generated
     */
    public Date getPasswordUpdateTime() {
        return passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password_update_time
     *
     * @param passwordUpdateTime the value for member.password_update_time
     *
     * @mbg.generated
     */
    public void setPasswordUpdateTime(Date passwordUpdateTime) {
        this.passwordUpdateTime = passwordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.registration_ip
     *
     * @return the value of member.registration_ip
     *
     * @mbg.generated
     */
    public String getRegistrationIp() {
        return registrationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.registration_ip
     *
     * @param registrationIp the value for member.registration_ip
     *
     * @mbg.generated
     */
    public void setRegistrationIp(String registrationIp) {
        this.registrationIp = registrationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.locked
     *
     * @return the value of member.locked
     *
     * @mbg.generated
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.locked
     *
     * @param locked the value for member.locked
     *
     * @mbg.generated
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.enabled
     *
     * @return the value of member.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.enabled
     *
     * @param enabled the value for member.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password_expiration_time
     *
     * @return the value of member.password_expiration_time
     *
     * @mbg.generated
     */
    public Date getPasswordExpirationTime() {
        return passwordExpirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password_expiration_time
     *
     * @param passwordExpirationTime the value for member.password_expiration_time
     *
     * @mbg.generated
     */
    public void setPasswordExpirationTime(Date passwordExpirationTime) {
        this.passwordExpirationTime = passwordExpirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.description
     *
     * @return the value of member.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.description
     *
     * @param description the value for member.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth_day
     *
     * @return the value of member.birth_day
     *
     * @mbg.generated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth_day
     *
     * @param birthDay the value for member.birth_day
     *
     * @mbg.generated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", totp=").append(totp);
        sb.append(", name=").append(name);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", gender=").append(gender);
        sb.append(", createTime=").append(createTime);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", errorCount=").append(errorCount);
        sb.append(", passwordUpdateTime=").append(passwordUpdateTime);
        sb.append(", registrationIp=").append(registrationIp);
        sb.append(", locked=").append(locked);
        sb.append(", enabled=").append(enabled);
        sb.append(", passwordExpirationTime=").append(passwordExpirationTime);
        sb.append(", description=").append(description);
        sb.append(", birthDay=").append(birthDay);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Member other = (Member) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getTotp() == null ? other.getTotp() == null : this.getTotp().equals(other.getTotp()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getLockTime() == null ? other.getLockTime() == null : this.getLockTime().equals(other.getLockTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getErrorCount() == null ? other.getErrorCount() == null : this.getErrorCount().equals(other.getErrorCount()))
            && (this.getPasswordUpdateTime() == null ? other.getPasswordUpdateTime() == null : this.getPasswordUpdateTime().equals(other.getPasswordUpdateTime()))
            && (this.getRegistrationIp() == null ? other.getRegistrationIp() == null : this.getRegistrationIp().equals(other.getRegistrationIp()))
            && (this.getLocked() == null ? other.getLocked() == null : this.getLocked().equals(other.getLocked()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getPasswordExpirationTime() == null ? other.getPasswordExpirationTime() == null : this.getPasswordExpirationTime().equals(other.getPasswordExpirationTime()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getBirthDay() == null ? other.getBirthDay() == null : this.getBirthDay().equals(other.getBirthDay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getTotp() == null) ? 0 : getTotp().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getLockTime() == null) ? 0 : getLockTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getErrorCount() == null) ? 0 : getErrorCount().hashCode());
        result = prime * result + ((getPasswordUpdateTime() == null) ? 0 : getPasswordUpdateTime().hashCode());
        result = prime * result + ((getRegistrationIp() == null) ? 0 : getRegistrationIp().hashCode());
        result = prime * result + ((getLocked() == null) ? 0 : getLocked().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getPasswordExpirationTime() == null) ? 0 : getPasswordExpirationTime().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getBirthDay() == null) ? 0 : getBirthDay().hashCode());
        return result;
    }
}