package net.renfei.server.cms.repositories;

import java.util.List;
import net.renfei.server.cms.repositories.entity.CmsArticleTag;
import net.renfei.server.cms.repositories.entity.CmsArticleTagExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CmsArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    long countByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int deleteByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int insert(CmsArticleTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticleTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    List<CmsArticleTag> selectByExample(CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    CmsArticleTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CmsArticleTag row, @Param("example") CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CmsArticleTag row, @Param("example") CmsArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsArticleTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsArticleTag row);
}