package net.renfei.server.cms.repositories;

import java.util.List;
import net.renfei.server.cms.repositories.entity.CmsArticles;
import net.renfei.server.cms.repositories.entity.CmsArticlesExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CmsArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    long countByExample(CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int deleteByExample(CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int insert(CmsArticles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExampleWithBLOBs(CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExample(CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    CmsArticles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CmsArticles row, @Param("example") CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CmsArticles row, @Param("example") CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CmsArticles row, @Param("example") CmsArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsArticles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CmsArticles row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsArticles row);
}