package net.renfei.server.cms.repositories;

import java.util.List;
import net.renfei.server.cms.repositories.entity.CmsArticleVersions;
import net.renfei.server.cms.repositories.entity.CmsArticleVersionsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CmsArticleVersionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    long countByExample(CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int deleteByExample(CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int insert(CmsArticleVersions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticleVersions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    List<CmsArticleVersions> selectByExampleWithBLOBs(CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    List<CmsArticleVersions> selectByExample(CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    CmsArticleVersions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CmsArticleVersions row, @Param("example") CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CmsArticleVersions row, @Param("example") CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CmsArticleVersions row, @Param("example") CmsArticleVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsArticleVersions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CmsArticleVersions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsArticleVersions row);
}