package net.renfei.server.cms.repositories;

import java.util.List;
import net.renfei.server.cms.repositories.entity.CmsTags;
import net.renfei.server.cms.repositories.entity.CmsTagsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CmsTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    long countByExample(CmsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int deleteByExample(CmsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int insert(CmsTags row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int insertSelective(CmsTags row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    List<CmsTags> selectByExample(CmsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    CmsTags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CmsTags row, @Param("example") CmsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CmsTags row, @Param("example") CmsTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsTags row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsTags row);
}