package net.renfei.server.cms.repositories.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   文章历史版本表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_article_versions
 */
public class CmsArticleVersions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   原始文章ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   文章封面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.cover_image
     *
     * @mbg.generated
     */
    private String coverImage;

    /**
     * Database Column Remarks:
     *   作者用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.author_name
     *
     * @mbg.generated
     */
    private String authorName;

    /**
     * Database Column Remarks:
     *   作者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.author_id
     *
     * @mbg.generated
     */
    private Long authorId;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.publish_date
     *
     * @mbg.generated
     */
    private Date publishDate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   状态：PUBLISH/REVISION/DELETED/OFFLINE/REVIEW
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   浏览量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.views
     *
     * @mbg.generated
     */
    private Long views;

    /**
     * Database Column Remarks:
     *   评论状态：OPENED/CLOSED
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.comment_status
     *
     * @mbg.generated
     */
    private String commentStatus;

    /**
     * Database Column Remarks:
     *   密码保护
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.versions
     *
     * @mbg.generated
     */
    private Integer versions;

    /**
     * Database Column Remarks:
     *   保密等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.secret_level
     *
     * @mbg.generated
     */
    private Integer secretLevel;

    /**
     * Database Column Remarks:
     *   是否原创
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.is_original
     *
     * @mbg.generated
     */
    private Boolean isOriginal;

    /**
     * Database Column Remarks:
     *   公文：索引号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.index_number
     *
     * @mbg.generated
     */
    private String indexNumber;

    /**
     * Database Column Remarks:
     *   公文：发文机关
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.document_issuing_agency
     *
     * @mbg.generated
     */
    private String documentIssuingAgency;

    /**
     * Database Column Remarks:
     *   公文：成文日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.written_date
     *
     * @mbg.generated
     */
    private Date writtenDate;

    /**
     * Database Column Remarks:
     *   公文：发文字号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.issued_number
     *
     * @mbg.generated
     */
    private String issuedNumber;

    /**
     * Database Column Remarks:
     *   公文：公文种类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.official_doc_category
     *
     * @mbg.generated
     */
    private String officialDocCategory;

    /**
     * Database Column Remarks:
     *   来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     * Database Column Remarks:
     *   来源链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     * Database Column Remarks:
     *   点赞量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.thumbs_up
     *
     * @mbg.generated
     */
    private Long thumbsUp;

    /**
     * Database Column Remarks:
     *   点踩量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.thumbs_down
     *
     * @mbg.generated
     */
    private Long thumbsDown;

    /**
     * Database Column Remarks:
     *   文章预览时长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.read_time
     *
     * @mbg.generated
     */
    private String readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.word_count
     *
     * @mbg.generated
     */
    private Long wordCount;

    /**
     * Database Column Remarks:
     *   文章内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_versions.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.id
     *
     * @return the value of cms_article_versions.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.id
     *
     * @param id the value for cms_article_versions.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.article_id
     *
     * @return the value of cms_article_versions.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.article_id
     *
     * @param articleId the value for cms_article_versions.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.title
     *
     * @return the value of cms_article_versions.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.title
     *
     * @param title the value for cms_article_versions.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.keyword
     *
     * @return the value of cms_article_versions.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.keyword
     *
     * @param keyword the value for cms_article_versions.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.description
     *
     * @return the value of cms_article_versions.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.description
     *
     * @param description the value for cms_article_versions.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.category_id
     *
     * @return the value of cms_article_versions.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.category_id
     *
     * @param categoryId the value for cms_article_versions.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.cover_image
     *
     * @return the value of cms_article_versions.cover_image
     *
     * @mbg.generated
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.cover_image
     *
     * @param coverImage the value for cms_article_versions.cover_image
     *
     * @mbg.generated
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.author_name
     *
     * @return the value of cms_article_versions.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.author_name
     *
     * @param authorName the value for cms_article_versions.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.author_id
     *
     * @return the value of cms_article_versions.author_id
     *
     * @mbg.generated
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.author_id
     *
     * @param authorId the value for cms_article_versions.author_id
     *
     * @mbg.generated
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.publish_date
     *
     * @return the value of cms_article_versions.publish_date
     *
     * @mbg.generated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.publish_date
     *
     * @param publishDate the value for cms_article_versions.publish_date
     *
     * @mbg.generated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.update_date
     *
     * @return the value of cms_article_versions.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.update_date
     *
     * @param updateDate the value for cms_article_versions.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.status
     *
     * @return the value of cms_article_versions.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.status
     *
     * @param status the value for cms_article_versions.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.views
     *
     * @return the value of cms_article_versions.views
     *
     * @mbg.generated
     */
    public Long getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.views
     *
     * @param views the value for cms_article_versions.views
     *
     * @mbg.generated
     */
    public void setViews(Long views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.comment_status
     *
     * @return the value of cms_article_versions.comment_status
     *
     * @mbg.generated
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.comment_status
     *
     * @param commentStatus the value for cms_article_versions.comment_status
     *
     * @mbg.generated
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.password
     *
     * @return the value of cms_article_versions.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.password
     *
     * @param password the value for cms_article_versions.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.versions
     *
     * @return the value of cms_article_versions.versions
     *
     * @mbg.generated
     */
    public Integer getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.versions
     *
     * @param versions the value for cms_article_versions.versions
     *
     * @mbg.generated
     */
    public void setVersions(Integer versions) {
        this.versions = versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.secret_level
     *
     * @return the value of cms_article_versions.secret_level
     *
     * @mbg.generated
     */
    public Integer getSecretLevel() {
        return secretLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.secret_level
     *
     * @param secretLevel the value for cms_article_versions.secret_level
     *
     * @mbg.generated
     */
    public void setSecretLevel(Integer secretLevel) {
        this.secretLevel = secretLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.is_original
     *
     * @return the value of cms_article_versions.is_original
     *
     * @mbg.generated
     */
    public Boolean getIsOriginal() {
        return isOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.is_original
     *
     * @param isOriginal the value for cms_article_versions.is_original
     *
     * @mbg.generated
     */
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.index_number
     *
     * @return the value of cms_article_versions.index_number
     *
     * @mbg.generated
     */
    public String getIndexNumber() {
        return indexNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.index_number
     *
     * @param indexNumber the value for cms_article_versions.index_number
     *
     * @mbg.generated
     */
    public void setIndexNumber(String indexNumber) {
        this.indexNumber = indexNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.document_issuing_agency
     *
     * @return the value of cms_article_versions.document_issuing_agency
     *
     * @mbg.generated
     */
    public String getDocumentIssuingAgency() {
        return documentIssuingAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.document_issuing_agency
     *
     * @param documentIssuingAgency the value for cms_article_versions.document_issuing_agency
     *
     * @mbg.generated
     */
    public void setDocumentIssuingAgency(String documentIssuingAgency) {
        this.documentIssuingAgency = documentIssuingAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.written_date
     *
     * @return the value of cms_article_versions.written_date
     *
     * @mbg.generated
     */
    public Date getWrittenDate() {
        return writtenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.written_date
     *
     * @param writtenDate the value for cms_article_versions.written_date
     *
     * @mbg.generated
     */
    public void setWrittenDate(Date writtenDate) {
        this.writtenDate = writtenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.issued_number
     *
     * @return the value of cms_article_versions.issued_number
     *
     * @mbg.generated
     */
    public String getIssuedNumber() {
        return issuedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.issued_number
     *
     * @param issuedNumber the value for cms_article_versions.issued_number
     *
     * @mbg.generated
     */
    public void setIssuedNumber(String issuedNumber) {
        this.issuedNumber = issuedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.official_doc_category
     *
     * @return the value of cms_article_versions.official_doc_category
     *
     * @mbg.generated
     */
    public String getOfficialDocCategory() {
        return officialDocCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.official_doc_category
     *
     * @param officialDocCategory the value for cms_article_versions.official_doc_category
     *
     * @mbg.generated
     */
    public void setOfficialDocCategory(String officialDocCategory) {
        this.officialDocCategory = officialDocCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.source
     *
     * @return the value of cms_article_versions.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.source
     *
     * @param source the value for cms_article_versions.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.source_url
     *
     * @return the value of cms_article_versions.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.source_url
     *
     * @param sourceUrl the value for cms_article_versions.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.thumbs_up
     *
     * @return the value of cms_article_versions.thumbs_up
     *
     * @mbg.generated
     */
    public Long getThumbsUp() {
        return thumbsUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.thumbs_up
     *
     * @param thumbsUp the value for cms_article_versions.thumbs_up
     *
     * @mbg.generated
     */
    public void setThumbsUp(Long thumbsUp) {
        this.thumbsUp = thumbsUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.thumbs_down
     *
     * @return the value of cms_article_versions.thumbs_down
     *
     * @mbg.generated
     */
    public Long getThumbsDown() {
        return thumbsDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.thumbs_down
     *
     * @param thumbsDown the value for cms_article_versions.thumbs_down
     *
     * @mbg.generated
     */
    public void setThumbsDown(Long thumbsDown) {
        this.thumbsDown = thumbsDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.read_time
     *
     * @return the value of cms_article_versions.read_time
     *
     * @mbg.generated
     */
    public String getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.read_time
     *
     * @param readTime the value for cms_article_versions.read_time
     *
     * @mbg.generated
     */
    public void setReadTime(String readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.word_count
     *
     * @return the value of cms_article_versions.word_count
     *
     * @mbg.generated
     */
    public Long getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.word_count
     *
     * @param wordCount the value for cms_article_versions.word_count
     *
     * @mbg.generated
     */
    public void setWordCount(Long wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_versions.content
     *
     * @return the value of cms_article_versions.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_versions.content
     *
     * @param content the value for cms_article_versions.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", articleId=").append(articleId);
        sb.append(", title=").append(title);
        sb.append(", keyword=").append(keyword);
        sb.append(", description=").append(description);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", coverImage=").append(coverImage);
        sb.append(", authorName=").append(authorName);
        sb.append(", authorId=").append(authorId);
        sb.append(", publishDate=").append(publishDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", status=").append(status);
        sb.append(", views=").append(views);
        sb.append(", commentStatus=").append(commentStatus);
        sb.append(", password=").append(password);
        sb.append(", versions=").append(versions);
        sb.append(", secretLevel=").append(secretLevel);
        sb.append(", isOriginal=").append(isOriginal);
        sb.append(", indexNumber=").append(indexNumber);
        sb.append(", documentIssuingAgency=").append(documentIssuingAgency);
        sb.append(", writtenDate=").append(writtenDate);
        sb.append(", issuedNumber=").append(issuedNumber);
        sb.append(", officialDocCategory=").append(officialDocCategory);
        sb.append(", source=").append(source);
        sb.append(", sourceUrl=").append(sourceUrl);
        sb.append(", thumbsUp=").append(thumbsUp);
        sb.append(", thumbsDown=").append(thumbsDown);
        sb.append(", readTime=").append(readTime);
        sb.append(", wordCount=").append(wordCount);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsArticleVersions other = (CmsArticleVersions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getKeyword() == null ? other.getKeyword() == null : this.getKeyword().equals(other.getKeyword()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getCoverImage() == null ? other.getCoverImage() == null : this.getCoverImage().equals(other.getCoverImage()))
            && (this.getAuthorName() == null ? other.getAuthorName() == null : this.getAuthorName().equals(other.getAuthorName()))
            && (this.getAuthorId() == null ? other.getAuthorId() == null : this.getAuthorId().equals(other.getAuthorId()))
            && (this.getPublishDate() == null ? other.getPublishDate() == null : this.getPublishDate().equals(other.getPublishDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getViews() == null ? other.getViews() == null : this.getViews().equals(other.getViews()))
            && (this.getCommentStatus() == null ? other.getCommentStatus() == null : this.getCommentStatus().equals(other.getCommentStatus()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getVersions() == null ? other.getVersions() == null : this.getVersions().equals(other.getVersions()))
            && (this.getSecretLevel() == null ? other.getSecretLevel() == null : this.getSecretLevel().equals(other.getSecretLevel()))
            && (this.getIsOriginal() == null ? other.getIsOriginal() == null : this.getIsOriginal().equals(other.getIsOriginal()))
            && (this.getIndexNumber() == null ? other.getIndexNumber() == null : this.getIndexNumber().equals(other.getIndexNumber()))
            && (this.getDocumentIssuingAgency() == null ? other.getDocumentIssuingAgency() == null : this.getDocumentIssuingAgency().equals(other.getDocumentIssuingAgency()))
            && (this.getWrittenDate() == null ? other.getWrittenDate() == null : this.getWrittenDate().equals(other.getWrittenDate()))
            && (this.getIssuedNumber() == null ? other.getIssuedNumber() == null : this.getIssuedNumber().equals(other.getIssuedNumber()))
            && (this.getOfficialDocCategory() == null ? other.getOfficialDocCategory() == null : this.getOfficialDocCategory().equals(other.getOfficialDocCategory()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getSourceUrl() == null ? other.getSourceUrl() == null : this.getSourceUrl().equals(other.getSourceUrl()))
            && (this.getThumbsUp() == null ? other.getThumbsUp() == null : this.getThumbsUp().equals(other.getThumbsUp()))
            && (this.getThumbsDown() == null ? other.getThumbsDown() == null : this.getThumbsDown().equals(other.getThumbsDown()))
            && (this.getReadTime() == null ? other.getReadTime() == null : this.getReadTime().equals(other.getReadTime()))
            && (this.getWordCount() == null ? other.getWordCount() == null : this.getWordCount().equals(other.getWordCount()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_versions
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getKeyword() == null) ? 0 : getKeyword().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getCoverImage() == null) ? 0 : getCoverImage().hashCode());
        result = prime * result + ((getAuthorName() == null) ? 0 : getAuthorName().hashCode());
        result = prime * result + ((getAuthorId() == null) ? 0 : getAuthorId().hashCode());
        result = prime * result + ((getPublishDate() == null) ? 0 : getPublishDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getViews() == null) ? 0 : getViews().hashCode());
        result = prime * result + ((getCommentStatus() == null) ? 0 : getCommentStatus().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getVersions() == null) ? 0 : getVersions().hashCode());
        result = prime * result + ((getSecretLevel() == null) ? 0 : getSecretLevel().hashCode());
        result = prime * result + ((getIsOriginal() == null) ? 0 : getIsOriginal().hashCode());
        result = prime * result + ((getIndexNumber() == null) ? 0 : getIndexNumber().hashCode());
        result = prime * result + ((getDocumentIssuingAgency() == null) ? 0 : getDocumentIssuingAgency().hashCode());
        result = prime * result + ((getWrittenDate() == null) ? 0 : getWrittenDate().hashCode());
        result = prime * result + ((getIssuedNumber() == null) ? 0 : getIssuedNumber().hashCode());
        result = prime * result + ((getOfficialDocCategory() == null) ? 0 : getOfficialDocCategory().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getSourceUrl() == null) ? 0 : getSourceUrl().hashCode());
        result = prime * result + ((getThumbsUp() == null) ? 0 : getThumbsUp().hashCode());
        result = prime * result + ((getThumbsDown() == null) ? 0 : getThumbsDown().hashCode());
        result = prime * result + ((getReadTime() == null) ? 0 : getReadTime().hashCode());
        result = prime * result + ((getWordCount() == null) ? 0 : getWordCount().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}