package net.renfei.server.cms.repositories.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   文章分类表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_article_category
 */
public class CmsArticleCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_category.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   父级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_category.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     * Database Column Remarks:
     *   英文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_category.category_en_name
     *
     * @mbg.generated
     */
    private String categoryEnName;

    /**
     * Database Column Remarks:
     *   中文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_category.category_zh_name
     *
     * @mbg.generated
     */
    private String categoryZhName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_category.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_category.id
     *
     * @return the value of cms_article_category.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_category.id
     *
     * @param id the value for cms_article_category.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_category.pid
     *
     * @return the value of cms_article_category.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_category.pid
     *
     * @param pid the value for cms_article_category.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_category.category_en_name
     *
     * @return the value of cms_article_category.category_en_name
     *
     * @mbg.generated
     */
    public String getCategoryEnName() {
        return categoryEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_category.category_en_name
     *
     * @param categoryEnName the value for cms_article_category.category_en_name
     *
     * @mbg.generated
     */
    public void setCategoryEnName(String categoryEnName) {
        this.categoryEnName = categoryEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_category.category_zh_name
     *
     * @return the value of cms_article_category.category_zh_name
     *
     * @mbg.generated
     */
    public String getCategoryZhName() {
        return categoryZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_category.category_zh_name
     *
     * @param categoryZhName the value for cms_article_category.category_zh_name
     *
     * @mbg.generated
     */
    public void setCategoryZhName(String categoryZhName) {
        this.categoryZhName = categoryZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_category.description
     *
     * @return the value of cms_article_category.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_category.description
     *
     * @param description the value for cms_article_category.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", categoryEnName=").append(categoryEnName);
        sb.append(", categoryZhName=").append(categoryZhName);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_category
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsArticleCategory other = (CmsArticleCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getCategoryEnName() == null ? other.getCategoryEnName() == null : this.getCategoryEnName().equals(other.getCategoryEnName()))
            && (this.getCategoryZhName() == null ? other.getCategoryZhName() == null : this.getCategoryZhName().equals(other.getCategoryZhName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_category
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getCategoryEnName() == null) ? 0 : getCategoryEnName().hashCode());
        result = prime * result + ((getCategoryZhName() == null) ? 0 : getCategoryZhName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}