package net.renfei.server.cms.repositories.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   标签表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_tags
 */
public class CmsTags implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tags.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   标签英文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tags.tag_en_name
     *
     * @mbg.generated
     */
    private String tagEnName;

    /**
     * Database Column Remarks:
     *   标签中文名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tags.tag_zh_name
     *
     * @mbg.generated
     */
    private String tagZhName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tags.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tags.id
     *
     * @return the value of cms_tags.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tags.id
     *
     * @param id the value for cms_tags.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tags.tag_en_name
     *
     * @return the value of cms_tags.tag_en_name
     *
     * @mbg.generated
     */
    public String getTagEnName() {
        return tagEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tags.tag_en_name
     *
     * @param tagEnName the value for cms_tags.tag_en_name
     *
     * @mbg.generated
     */
    public void setTagEnName(String tagEnName) {
        this.tagEnName = tagEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tags.tag_zh_name
     *
     * @return the value of cms_tags.tag_zh_name
     *
     * @mbg.generated
     */
    public String getTagZhName() {
        return tagZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tags.tag_zh_name
     *
     * @param tagZhName the value for cms_tags.tag_zh_name
     *
     * @mbg.generated
     */
    public void setTagZhName(String tagZhName) {
        this.tagZhName = tagZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tags.description
     *
     * @return the value of cms_tags.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tags.description
     *
     * @param description the value for cms_tags.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tagEnName=").append(tagEnName);
        sb.append(", tagZhName=").append(tagZhName);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsTags other = (CmsTags) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTagEnName() == null ? other.getTagEnName() == null : this.getTagEnName().equals(other.getTagEnName()))
            && (this.getTagZhName() == null ? other.getTagZhName() == null : this.getTagZhName().equals(other.getTagZhName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tags
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTagEnName() == null) ? 0 : getTagEnName().hashCode());
        result = prime * result + ((getTagZhName() == null) ? 0 : getTagZhName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}