server:
  port: 9595

spring:
  profiles:
    active: @profiles.active@

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-login-endpoint: true
  show-oauth2-endpoints: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml

pagehelper:
  helperDialect: mariadb
  reasonable: true
  supportMethodsArguments: true
