package net.renfei.server.core.repositories;

import java.util.List;
import net.renfei.server.core.repositories.entity.SysAuditLog;
import net.renfei.server.core.repositories.entity.SysAuditLogExample;
import net.renfei.server.core.repositories.entity.SysAuditLogWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysAuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    long countByExample(SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int deleteByExample(SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int insert(SysAuditLogWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int insertSelective(SysAuditLogWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    List<SysAuditLogWithBLOBs> selectByExampleWithBLOBs(SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    List<SysAuditLog> selectByExample(SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    SysAuditLogWithBLOBs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SysAuditLogWithBLOBs row, @Param("example") SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SysAuditLogWithBLOBs row, @Param("example") SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SysAuditLog row, @Param("example") SysAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAuditLogWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SysAuditLogWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAuditLog row);
}